set( SRC_FILES
	src/main.cpp
	src/log.cpp
	src/input.cpp
	src/video.cpp
	src/video_audio.cpp
	src/video_manager.cpp
	src/file_manager.cpp
	src/file.cpp
	src/carousel.cpp
	src/database.cpp
	src/texture_manager.cpp
	src/graphics/renderer.cpp
	src/graphics/color.cpp
	src/graphics/png_texture.cpp
	src/graphics/video_texture.cpp
	src/states/search_state.cpp
	src/states/state_manager.cpp
	src/states/initial_state.cpp
	src/states/browse_state.cpp
	src/states/root_state.cpp
	src/states/video_state.cpp
	src/sort/merge_sort.cpp
)
