set( SRC_FILES 
    src/Main.cpp
    src/Logger.cpp
    src/controllers/IoWriteController.cpp
    src/controllers/IoReadController.cpp
    src/controllers/IoDestructionController.cpp
    src/controllers/IoCreationController.cpp
    src/controllers/TestController.cpp
    src/tests/UnitTest.cpp
    src/tests/TestIoReadController.cpp
    src/tests/TestIoWriteController.cpp
    src/tests/TestIoCreationController.cpp
    src/tests/TestIoDestructionController.cpp
    src/tests/TestColor.cpp
    src/rendering/Renderer.cpp
    src/rendering/RenderObject.cpp
    src/rendering/Color.cpp
    src/rendering/Transform.cpp
    src/rendering/Triangle.cpp
)